package eulerproject;

/*
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

/**
 *
 * @author cstauber77
 */
public class ProblemTwo {
    
    public static void fibGenerator() {
        
        int num1 = 0;
        int num2 = 1;
        int sum = 0;
        
        int temp;
        
        while(num2 < 4000000){
            temp = num2;
            num2 = num1 + num2;
            num1 = temp;
            if(num2%2 ==0){
                sum += num2; 
            }
        }
        System.out.println(sum);
        
    }
    
}
